version 18.0
clear all
set more off
set varabbrev off

* ------------------------------------------------------------
* Replication assignment template: Stata -> PDF directly
* First run this file unchanged. Then replace the example parts.
* ------------------------------------------------------------

local student_id "Your Student ID"
local student    "Your Name"
local assignment "Advanced Econometric Methods:sample"

* Open the file supplied for the current assignment here.
sysuse auto, clear

* Reader-friendly labels used in output
label variable price  "Vehicle price (US dollars)"
label variable mpg    "Fuel economy (miles per gallon)"
label variable weight "Vehicle weight (pounds)"

* Analysis
summarize price mpg weight
capture estimates drop model1
quietly regress price mpg weight
estimates store model1

* Figure generated by code
twoway (scatter price mpg) (lfit price mpg), ///
    title("Vehicle price and fuel economy") ///
    xtitle("Fuel economy (miles per gallon)") ///
    ytitle("Vehicle price (US dollars)") ///
    legend(order(1 "Observed" 2 "Linear fit"))
graph export "figure1.png", width(1600) replace

* Build the English report
capture putpdf clear
putpdf begin

putpdf paragraph, halign(center)
putpdf text ("`assignment'"), bold font("Arial", 18)
putpdf paragraph, halign(center)
putpdf text ("Student ID: `student_id'"), font("Arial", 11)
putpdf paragraph, halign(center)
putpdf text ("`student'"), font("Arial", 11)

putpdf paragraph
putpdf text ("[Question number and short title]"), bold font("Arial", 14)
putpdf paragraph
putpdf text ("Answer the question directly. Explain the direction, magnitude, and substantive meaning of the main result.")

putpdf paragraph, halign(center)
putpdf image "figure1.png", width(5)
putpdf paragraph, halign(center)
putpdf text ("Figure 1. Vehicle price and fuel economy")

putpdf paragraph
putpdf text ("[Next question number and short title]"), bold font("Arial", 14)
putpdf paragraph
putpdf text ("The following table demonstrates how to insert estimation results.")
* etable needs active estimation results. Restore the saved model first.
* Run this do-file from the beginning; do not run only the next line.
estimates restore model1
putpdf table table1 = etable

putpdf paragraph
putpdf text ("Brief interpretation: ...")

* Copy the question paragraphs above as many times as needed. Follow the
* numbering and order used in the current assignment.

putpdf save "replication_report.pdf", replace
